# Generated by Django 5.2 on 2025-05-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brandcloth', '0002_productlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductList',
        ),
    ]
