# Generated by Django 5.2 on 2025-06-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandcloth', '0004_cartitem_price_journal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
